import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

import Match from "@/components/match/match";
import Ranked from "@/components/table/ranked/rankedTable";
import Team from "@/components/table/team/teamTable";

const Open_Sans_init = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body
        className={`${Open_Sans_init.className} py-4 pl-48 pr-48 mx-auto text-[#242423] bg-[#E9E9E9] selection:bg-[#242423] selection:text-white`}
      >
        <Header />
        <Match />
        <Ranked />
        <Team />
      </body>
    </html>
  );
}
